### ISSUE TITLE
CLI overlapping

### ISSUE THREAD

**Issue by Syque** [npkgz/cli-progress#105]
![image](https://user-images.githubusercontent.com/60582843/124486667-80d28a00-ddb6-11eb-8a2e-92bded42c219.png)

How could I fix this ? 

As the script finishes the stdout buffer still dumps some text on top.

**Comment by AndiDittrich** [comment]
cli-progress require exclusive access to the tty terminal. you have to take care that other processes not using it (e.g. redirect the streams..)
