### ISSUE TITLE
Support for Deno?

### ISSUE THREAD

**Issue by yakesho** [npkgz/cli-progress#106]
Would it be possible to support [Deno](https://deno.land/ 'Deno') for this project? Would be great if you can add Deno support for this project. It's a cool project I must say

**Comment by AndiDittrich** [comment]
contributions are welcome. atm i didn't have any idea about the differences between Deno and Node.js runtime.

what's not working ?

**Comment by yakesho** [comment]
Dependencies on Deno don't work the same as Node does. Deno uses URL to import dependencies.

Maybe I can contribute if you want but I'm quite busy this week
