### ISSUE TITLE
no progress bar on NPM

### ISSUE THREAD

**Issue by yosion-p** [npkgz/cli-progress#107]
**Describe** ：
We used cli-progress in the project, which is normal in the development environment; Then we released our project on NPM, ran it with the project on NPM, and found that the progress bar cannot be displayed on gitbash；
This is the NPM link for our project：[https://www.npmjs.com/package/@originjs/webpack-to-vite](url)；
and this is our Repository: [https://github.com/originjs/webpack-to-vite](url);

**How To Reproduce:**
1. download
```
npm install @originjs/webpack-to-vite -g
```
2. convert
```
webpack-to-vite -d <project path>
```
![image](https://user-images.githubusercontent.com/86145334/128119370-f122f09d-b369-454b-8b14-2b4f2b6ba104.png)
The first line of command in the picture uses the development environment, and the result is normal;
`node ./dist/bin/index -d ../project-to-test/vue-manage-system`
The second line of code is the package published after NPM, and the progress bar is not displayed。
`webpack-to-vite -d ../project-to-test/vue-manage-system`

**Environment Version Description: **
OS: windows 64
gitBash: Git-2.31.1-64-bit
Repository of  Conversion project：[https://github.com/lin-xin/vue-manage-system.git ](url) （branch is  _dev_)

========That's all=========

**Comment by AndiDittrich** [comment]
Hi @yosion-p 

it sounds like a "known" issue regarding the `isTTY` check on windows systems (cmd.exe, gitbash). it's caused by the invocation by the `.bat` file instead of a direct call via node interpreter.

in the past, the issue didn't appeared in PowerShell.

**Comment by yosion-p** [comment]
> Hi @yosion-p
> 
> it sounds like a "known" issue regarding the `isTTY` check on windows systems (cmd.exe, gitbash). it's caused by the invocation by the `.bat` file instead of a direct call via node interpreter.
> 
> in the past, the issue didn't appeared in PowerShell.

Thank you for your reply;
Indeed, this problem only appears on gitbash.
