### ISSUE TITLE
ETA is incorrect for consistently timed countdown

### ISSUE THREAD

**Issue by PixelNinja132** [npkgz/cli-progress#108]
Hi,

I'm making a Discord bot and I'm using this to have a percentage of shards loaded. If I have a 20 goal progress bar, each shard takes 5 seconds to boot, but even after about 5 shards loading, the ETA is still inaccurate. The ETA should be a rolling average of the past updates multiplied by the number of upcoming ones. 

Could this be an added mode?

Thanks

**Comment by AndiDittrich** [comment]
just use your own eta calculation and provide the eta as payload.

**Comment by cmdcolin** [comment]
if I understand correctly, I would also be interested in this feature. I could roll my own but...maybe having it as an optional built in :)

e.g. a long download time has rapidly updating/highly variable ETA where it could try to average perhaps

**Comment by AndiDittrich** [comment]
the current eta calculation uses a average value over the last n samples, where `n` can be controlled via `etaBuffer`. Depending of the number of calls to `update` this value needs to be adjusted (default 10). in some cases the asynchronous eta update also helps.

see: https://github.com/npkgz/cli-progress/blob/master/lib/eta.js

-----------

in the past there where a several requests regarding "other" algorithms but in most situations there is no universal solution. the current delta average calculation also works fine with non-linear updates.

if someone has ideas for additional algorithms they can be integrated soon, but take care that most applications `update` calls doesn't have a constant delta_t/period
