### ISSUE TITLE
Issue when MultiBar overflowed terminal height

### ISSUE THREAD

**Issue by mddarmawan** [npkgz/cli-progress#109]
Hi, thanks for a great package, much appreciate it!

However, I am using this package to show multiple progress bars (around 200 bars) and when the height is overflowed, the bars start scrolling with an unintended view. As shown from this video:

https://user-images.githubusercontent.com/22543134/130545079-9098acd0-c036-4690-9fb4-bc4afff45b15.mov

Thanks!

**Comment by AndiDittrich** [comment]
see duplicate issue #59 
currently there is no solution available

**Comment by mddarmawan** [comment]
Thanks!
