### ISSUE TITLE
Usage in multithreading (cluster)

### ISSUE THREAD

**Issue by kolykhalov** [npkgz/cli-progress#114]
Hello world! :)

How to use cli-progress in cluster mode (const cluster=require('cluster')) per every worker so that it writes progress-bars independently? Currently if I use SingeBar every update rewrites the current bar from every worker in single line. How to make it update multiline and not overlap each other? Single threaded works like a charm.

Expected:

Master bar:    [=======            ]
Worker 1 bar: [==                        ]
Worker 2 bar: [=========       ]

**Comment by AndiDittrich** [comment]
you have to use a dedicated worker (master( thread which manages the UI components (progress bar). each worker thread has to pass it's status via the build-in messaging system to it

**Comment by kolykhalov** [comment]
Hello Andi! Thanks for your help and this beautiful library.

**Comment by cfmj** [comment]
> you have to use a dedicated worker (master( thread which manages the UI components (progress bar). each worker thread has to pass it's status via the build-in messaging system to it

can u give some code ?
