### ISSUE TITLE
typo in ReadMe: constious → continuous?

### ISSUE THREAD

**Issue by YDX-2147483647** [npkgz/cli-progress#115]
Great project 👍, however 2nd row in [README.md#Features](https://github.com/npkgz/cli-progress#features):

> Full customizable output format (**constious** placeholders are available)

Is it *continuous*?

**Comment by AndiDittrich** [comment]
thx, not shure what happend in the related commit https://github.com/npkgz/cli-progress/commit/68e219037155a5bb51368764425427a3b1398977
