### ISSUE TITLE
Require fails when compiled with pkg for windows

### ISSUE THREAD

**Issue by KCGD** [npkgz/cli-progress#118]
This package works perfectly when running normally on node and when compiled for linux. However, when it is compiled for windows the require fails with no error given. The process just closes.

**Comment by AndiDittrich** [comment]
right now i'm not having any resources (neither windows nor enough time) to debug the issue on windows. i can give you some hints but you have to debug it on your own - e.g. start with a minimal example using the cli-progress git repository.

**Comment by KCGD** [comment]
I just ended making my own version cli-progress, I'm not entirely sure what made the last one fail but the one I wrote works. I'll upload it soon.
