### ISSUE TITLE
Logs Swallowing while using cli-progress.

### ISSUE THREAD

**Issue by ryanhssn** [npkgz/cli-progress#120]
Hey guys, first of all this is a very good plugin. Thanks for that.
The problem I just discovered is that when I use this plugin, my terminal log gets truncated after the first line.
At first I thought it was a terminal issue, but then I tried some other terminals and found the same behavior.

**Issue** - When using the package, only the first line of the log file is shown in the terminal. Break from line 2, he shows nothing but a new diary.

**node -v 14.17.0
cli-progress 3.10.0**

**Comment by AndiDittrich** [comment]
Hi @ryanhssn 

please provide a minimal! code example to reproduce the issue. thanks

btw. you cannot use progress-bars and output something to the terminal in parallel! see other threads for possible workarounds
