### ISSUE TITLE
Multi-bar with different options per bar

### ISSUE THREAD

**Issue by justarandomgeek** [npkgz/cli-progress#122]
I'd like to use a multi-bar to represent a hierarchy of ongoing tasks, and for most of the "parent" tasks, i just want the count of child tasks displayed but for the file-download tasks at the bottom of the tree i'd like to use a custom formatter to show filesize and custom payload to show speed. Would it be possible to have option overrides per-bar within a multi-bar container to allow things like this?

**Comment by AndiDittrich** [comment]
a custom-formatter is the intended solution - but technically cli-progress is not designed for such tasks

**Comment by justarandomgeek** [comment]
I guess i'm not clear on how a custom formatter is supposed to achieve this then - I don't see how/where i would pass the per-bar options in to make it behave differently? I am already using a custom value formatter for the filesizes, but then it applies to *all* the bars!

**Comment by justarandomgeek** [comment]
and what is multi-bar for if not for showing concurrent tasks? I just want to have a header bar showing how many of the total queued tasks have completed above the bars for the active tasks

**Comment by AndiDittrich** [comment]
check the docs - `format` can be a string or a custom function to override the default formatter. you can just output a header text instead of a bar.

"fancy" features like headers or logging are currently not implemented (i didn't have any resources left to add this stuff at the moment)

**Comment by justarandomgeek** [comment]
yes, i'm already using a custom formatting function, but that function doesn't get anything to identify which bar it's currently rendering so it can't choose *which* kind of formatting to apply, how would i do that?

**Comment by AndiDittrich** [comment]
use the events, custom payloads or modify the code to pass an index

**Comment by justarandomgeek** [comment]
but the value formatter doesn't get any other parts of teh payload data than the one it is formatting? how would i know which kind of formatting to apply there?

**Comment by AndiDittrich** [comment]
you can use the events to set a flag, or pass a custom payload to the special bar like "isHeader: true", or modify the cli-progress sourcecode and pass the actual index as parameter

**Comment by AndiDittrich** [comment]
is this that difficult ? ...

```js
// create new container
const multibar = new _progress.MultiBar({
    format: function(options, params, payload){
        
        if (payload.isHeader){
            return _progress.Format.Formatter(Object.assign({}, options, {
                format: "Overall Progress [{bar}]"
            }), params, payload);
        }

        return _progress.Format.Formatter(Object.assign({}, options, {
            format: "progress [{bar}] {percentage}% | ETA: {eta}s | {value}/{total}"
        }), params, payload);
    },
    hideCursor: true,
    barCompleteChar: '\u2588',
    barIncompleteChar: '\u2591',
    clearOnComplete: true,
    stopOnComplete: true
});

multibar.create(1, 0, {isHeader: true})
```

**Comment by justarandomgeek** [comment]
https://github.com/justarandomgeek/cli-progress/commit/4e14a08de94a34e076b6bf29b693774516727e2f was far easier, even than that though!

**Comment by justarandomgeek** [comment]
Should I expect this any time soon? or am i going to be forced to actually use this ugly hack?

**Comment by AndiDittrich** [comment]
it's not an ugly hack...it's the intended usage of the custom formatter function

**Comment by justarandomgeek** [comment]
But it's a one line change to get per-bar options in a *far* simpler way

**Comment by justarandomgeek** [comment]
Well, in any case, I will be proceeding with my project using a local fork with this applied, I hope i won't have to end up publishing my own fork of this whole package just to get sensible multi-bar options!

**Comment by AndiDittrich** [comment]
do whatever you want

**Comment by justarandomgeek** [comment]
The idea that `format` is the intended way to access `options` is just patently absurd
