### ISSUE TITLE
[Bug] Does not work in docker-compose

### ISSUE THREAD

**Issue by MeddahAbdellah** [npkgz/cli-progress#124]
<img width="732" alt="Screenshot 2022-05-08 at 10 30 00" src="https://user-images.githubusercontent.com/32915429/167288123-9dcb8314-5525-4f2d-ac49-2c8f5c8a7019.png">
Instead of having the loading bar I just have an empty space

**Comment by AndiDittrich** [comment]
please provide a minimal example to reproduce the issue - additionally add infos of the used environment (shell/os/node version etc)
