### ISSUE TITLE
Payload does not work

### ISSUE THREAD

**Issue by paul-uz** [npkgz/cli-progress#128]
Same issue as here https://github.com/npkgz/cli-progress/issues/63

OP fixed it using the formatter, but I'd prefer it to work out of the box as per the documentation.

Can this be looked into?

**Comment by paul-uz** [comment]
https://github.com/npkgz/cli-progress/issues/63 only worked because they used the `format` option.

The documentation for using the payload (in a multibar, which is what I am using) does not show the `format` option being used with a payload, see here https://github.com/npkgz/cli-progress#example-1

I even tried using the payload key of `filename` like in the example, but that didn't work either.

It only works when using the `format` option.

**Comment by AndiDittrich** [comment]
ok sry, i've to add the format option to this particular example

**Comment by AndiDittrich** [comment]
docs have been updated
