### ISSUE TITLE
Add support for using chalk-animation and ora or nanospinner

### ISSUE THREAD

**Issue by leopinnheiro** [npkgz/cli-progress#130]
I don't know if "add support" is the correct phrase to use.
But these three libraries provide interesting functionality that might be interesting to have.

chalk-animation - enables animations in the terminal.
![image](https://camo.githubusercontent.com/19928fb8123f2f53f13a34e0f5c1dabe26021711274f3759a25bdfe28f37d781/687474703a2f2f692e696d6775722e636f6d2f6e61706478646e2e676966)

ora or nanospinner - Adds cool spinner controls indicating success, or failure.
![image](https://raw.githubusercontent.com/sindresorhus/ora/HEAD/screenshot.svg)
<img src="https://raw.githubusercontent.com/sindresorhus/ora/HEAD/screenshot-2.gif" width="200" />

**Comment by AndiDittrich** [comment]
Hi @leopinnheiro 

regarding chalk, colors or other styling libraries: they can be used within the format option (see examples)

animation libraries are quite difficult to integrated, because cli-progress requires full control of the terminal (redraw). therefore i didn't see any possibilities to integrate them

**Comment by laporeon** [comment]
Hi there, sorry to reopen this issue, but it's kinda the same topic. I've been trying to apply a custom style to the progress bar using [gradient-string](https://www.npmjs.com/package/gradient-string) and it's been quite difficult. So far I've accomplished to style my own personal variables, but the bar itself has been quite a challenge.

You said other styling libraries can be used, any tips for how to do this or this particularly library isn't fully compatible? I've seen a couple examples here and there using chalk, but the colors are very limited to me.

Thank you.
