### ISSUE TITLE
Question: Is there a way to ignore/hide log outputs?

### ISSUE THREAD

**Issue by StaysenseWesMelton** [npkgz/cli-progress#132]
We use Winston as a central log manager for some of our applications. When running local, winston is configured to print errors we capture to `console.log`. 

Is there a config option for cli-progress that will ignore/hide/swallow those console.log outputs so we don't get a series of partial progress bars?

Currently this is the output produced when our logger captures errors/warnings: 
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/111527254/206226728-b31daad6-ea50-4f07-8697-f61a112d1346.png">

**Comment by AndiDittrich** [comment]
please take a look into related logging issues: the progress bar requires full control of the stdout/sterr - you can use the event hooks to output messages in front of the bar but this requires a custom winston logger
