### ISSUE TITLE
Multibar does not show until multibar.stop() is called

### ISSUE THREAD

**Issue by jercle** [npkgz/cli-progress#134]
Have had a look around, but haven't been able to spot what I've done wrong, so not sure if it's a bug or PEBKAC

When using `cliProgress.MultiBar`, the bars do not show up until all is complete and `.stop()` is called, as shown in the below video.

https://user-images.githubusercontent.com/10472533/216513984-91830a51-049e-4cc7-a40a-dcf6fb9ecbe0.mov

In the below code, the bar only shows up after the first run of creating my `constructedFilteredList` object has completed. The `constructedFilteredList2` variable was only used as a quick check running code after `multibar.stop()` was called and moving it to after the 2nd only showed the bar after both were completed.

``` javascript
const getAllAppsWithUsers = () => {
  // This returns a version of the aggregated list that only includes apps that are not packaged.
  const fullInstalledList = getFullInstalledList().slice(0, 100000)

  const multibar = new cliProgress.MultiBar({
    clearOnComplete: false,
    hideCursor: true,
}, cliProgress.Presets.shades_grey);

  console.warn('Constructing list...')
  const listConstructionStart = new Date()
  const progressBar = multibar.create(Object.keys(fullInstalledList).length - 1, 0)
  // progressBar.start(Object.keys(fullInstalledList).length - 1, 0)
  const constructedFilteredList = fullInstalledList.reduce((all, item, index) => {
    progressBar.update(index)
    if (!all[item.appName]) {
      all[item.appName] = [item.username]
    } else {
      all[item.appName] = [...new Set([...all[item.appName], item.username])]
    }
    return all
  }, {})

  multibar.stop()
  
  console.warn(
    'List construction took',
    Math.round((new Date() - listConstructionStart) / 1000),
    'seconds'
  )

  console.log('testing multibar')
  const constructedFilteredList2 = fullInstalledList.reduce((all, item, index) => {
    if (!all[item.appName]) {
      all[item.appName] = [item.username]
    } else {
      all[item.appName] = [...new Set([...all[item.appName], item.username])]
    }
    return all
  }, {})
  return constructedFilteredList
}
```

**Comment by AndiDittrich** [comment]
the synchronous operation is blocking the timer event loop...a common js issue..
you can call `multibar.update()` explicitly on every `nth` element or use the single bar mode where `synchronousUpdate` can be used

**Comment by jercle** [comment]
> the synchronous operation is blocking the timer event loop...a common js issue.. you can call `multibar.update()` explicitly on every `nth` element or use the single bar mode where `synchronousUpdate` can be used

Ok awesome, works a treat, cheers!!!
Was absolutely doing my head in. Had a feeling it was something with the synchronous operation, but wasn't able to figure out getting around it with cli-progress.
