### ISSUE TITLE
Terminal.write() & console ANSI escape sequences

### ISSUE THREAD

**Issue by emmercm** [npkgz/cli-progress#135]
I have a custom format function that makes heavy use of `chalk` coloring:

https://github.com/emmercm/igir/blob/1ba176d54877dc01aafe13df2abe57ddd6fb2926/src/console/singleBarFormatted.ts#L30

(see the Asciicast in the project's readme for a video of how it renders)

The default formatter takes into account ANSI escape sequences by using `string-width` to calculate the true width of a string, but this is only for alignment. `Terminal.write()` doesn't use `string-width` and instead trims all lines to `process.stdout.columns`.

**Comment by emmercm** [comment]
I may have been too hasty with this issue, I think I misunderstood what this line is accomplishing, and instead, there is something else happening with my application:

https://github.com/npkgz/cli-progress/blob/f4dc17274fc433a6dc9d2fa3696e25283981d5f0/lib/formatter.js#L57

**Comment by emmercm** [comment]
I think it's because MultiBar, which has its own `Terminal` instance, sets `linewrap: false`:

https://github.com/npkgz/cli-progress/blob/f4dc17274fc433a6dc9d2fa3696e25283981d5f0/lib/multi-bar.js#L67-L70

but when it spawns new GenericBars:

https://github.com/npkgz/cli-progress/blob/f4dc17274fc433a6dc9d2fa3696e25283981d5f0/lib/multi-bar.js#L42-L43

those each get their own `Terminal` instance which default to `linewrap: true`:

https://github.com/npkgz/cli-progress/blob/f4dc17274fc433a6dc9d2fa3696e25283981d5f0/lib/generic-bar.js#L16

**Comment by AndiDittrich** [comment]
the hard-trimming within `terminal.write` was required to avoid issues on different platforms .. i know this might cause such issues - atm i've no "real "solution without adding a heavy library (slow!) which take the ascii sequences into account.

regarding the terminal instances: you're right, that looks weak .. i'm not shure why i've didn't passed the "global" instance to the generic bars. i've to take a look into

**Comment by emmercm** [comment]
You're right, I think my original post is incorrect here. I think it's because the `linewrap` setting isn't being respected for multi-bars.

**Comment by AndiDittrich** [comment]
i've applied the fix which uses the same terminal instance for all bars

**Comment by emmercm** [comment]
Confirmed that this fixed my issue! Sorry for the slow feedback.
