### ISSUE TITLE
Readme still says that `gracefulExit` defaults to `true`

### ISSUE THREAD

**Issue by NoahAndrews** [npkgz/cli-progress#137]
According to the [3.11.2 changelog](https://github.com/npkgz/cli-progress/blob/HEAD/CHANGES.md#3112), `gracefulExit` now defaults to `false`. 

The README also doesn't make it clear what the tradeoffs are that led to the default being set to `false`.

**Comment by AndiDittrich** [comment]
thanks for that hint, i've updated the docs - see https://github.com/npkgz/cli-progress/issues/126 for details
