### ISSUE TITLE
Logs being truncated after exiting process. 

### ISSUE THREAD

**Issue by adamawang** [npkgz/cli-progress#138]
Hi @AndiDittrich, this seems to be happening when you `ctrl+c` when a multibar is in progress. If you have a log that prints a long string of text that is more than one line, any subsequent line is truncated. Not sure what is happening there, could it be related to linewrap or clearline in the [terminal.js file](https://github.com/npkgz/cli-progress/blob/master/lib/terminal.js)?

Probably the same issue to https://github.com/npkgz/cli-progress/issues/120

To repro: 
```
exports.handler = async options => {
  logger.log(
    'Hi this is very long text. Hi this is very long text. Hi this is very long text. Hi this is very long text. Hi this is very long text. Hi this is very long text. Hi this is very long text. '
  );
  const multibar = new cliProgress.MultiBar(
    {
      hideCursor: true,
      format: '[{bar}] {percentage}% | {taskType}',
    },
    cliProgress.Presets.rect
  );
  const task1 = multibar.create(100, 0, { taskType: 'task 1' });
  const task2 = multibar.create(100, 0, { taskType: 'task 2' });

  for (let i = 0; i < 10; i++) {
    task1.increment(10, { taskType: 'task 1' });
    task2.increment(10, { taskType: 'task 2' });
    await new Promise(res => setTimeout(res, 1000));
  }
  multibar.stop();

  process.exit(EXIT_CODES.SUCCESS);
};
```

Screenshot of it happening, where between the two runs, I hit `ctrl + c` to stop the command:

<img width="717" alt="Screenshot 2023-03-09 at 17 33 42" src="https://user-images.githubusercontent.com/16788677/224150445-e7852e40-e1f0-4569-b8de-f3e46b68f5a9.png">

Version numbers:
```
"cli-progress": "^3.11.2",
"node": "18.7.0"
```

**Comment by AndiDittrich** [comment]
use `gracefulExit: true` - otherwise the terminal settings are not restored by the exit handler.
but keep in mind that you've to add a custom exit handler manually which terminates your app

**Comment by adamawang** [comment]
Awesome, thank you for the suggestion that seems to have worked!
