### ISSUE TITLE
Compatibility with gradient-string package

### ISSUE THREAD

**Issue by ghost** [npkgz/cli-progress#154]
Hi there. I've been trying to apply a custom style to the progress bar using [gradient-string](https://www.npmjs.com/package/gradient-string) and it's been quite difficult. So far I've accomplished to style my own personal variables, but the bar itself has been quite a challenge.

You said at a [closed issue](https://github.com/npkgz/cli-progress/issues/130) that styling libraries can be used, any tips for how to do this or this particularly library isn't fully compatible? I've seen a couple examples here and there using chalk, but the colors from chalk are very limited to me. 

Thank you.

**Comment by AndiDittrich** [comment]
you can provide custom bar formatters which are responsible for the bar rendering.
but any kind of "animation" would require a deep integration into the code...

**Comment by ghost** [comment]
Yeah, I thought so. I couldn't accomplish what I wanted in an easy way, but thanks anyway. I'm gonna close the issue.
