### ISSUE TITLE
Multibar can't show any logs

### ISSUE THREAD

**Issue by timsu92** [npkgz/cli-progress#156]
Here is a short program which I'm trying to use the logging function.
In the program, I set a maximum of 50 of the progress bar, and asks it to log when 0, 10, 20, 30, 40. However, what I see is the progress bar only. No any logs shown.
```ts
import { MultiBar } from "cli-progress";

const multibar = new MultiBar({
  hideCursor: true,
  clearOnComplete: true,
  stopOnComplete: true,
  forceRedraw: true,
});

const pro = multibar.create(50, 0, undefined, { autopadding: true });

for (let i = 0; i < 50; ++i) {
  pro.increment();
  if (i % 10 === 0) {
    multibar.log(i.toString());
  }
  await new Promise((resolve) => setTimeout(resolve, 50));
}
```

### Environment
OS: Ubuntu-22.04
Runtime: Bun v1.1.3

**Comment by saikatmitra91** [comment]
Replacing `multibar.log(i.toString());` with `multibar.log(i.toString() + "\n");` should work

**Comment by timsu92** [comment]
Thank you! Sorry for overlooking that comment in the example code.
