### ISSUE TITLE
TTY not in happy state if interrupted

### ISSUE THREAD

**Issue by reidrivenburgh** [npkgz/cli-progress#93]
Hi.  I've been happily using CLI-progress for a very long task, thank you.  Now I'm running into an issue when I interrupt (ctrl-c) the program while a progress bar is displayed.  It seems to put the tty into a confused state which can be fixed by doing a "reset" command in the shell.  (I'm using konsole and zsh on linux.)  I think I'm catching the event with process.on("SIGINT") and calling bar.stop(); do you think that should be enough to prevent this from happening?

Thanks,
Reid

**Comment by AndiDittrich** [comment]
you should add listeners to all kind of kill/term signals

**Comment by reidrivenburgh** [comment]
I am catching it successfully, since it prints a message.  And then I call bar.stop().  But it still leaves the tty in a wonky state, and I'm not sure why.  Just checking that calling stop() should be good enough.  Thanks.

**Comment by kosimas** [comment]
I can confirm this issue. The SIGINT event is triggerd after the task finished. Listening on SIGINT events and calling the .stop() method is not working. In my opinion, this event has to be catched by the Node.CLI-Progress libary.

**Comment by AndiDittrich** [comment]
i can add an optional flag to catch sigint/sigterm - but this might not work under all circumstances

**Comment by AndiDittrich** [comment]
this minimal snippet works as expected (bash)

```js
const bar1 = new _progress.SingleBar({}, _progress.Presets.shades_grey);
bar1.start(100, 0);

const timer = setInterval(() => {
    bar1.increment(5);
}, 500);

process.once('SIGINT', function() {
    clearInterval(timer);
    bar1.stop();
});

process.once('SIGTERM', function(){
    clearInterval(timer);
    bar1.stop();
});
```

**Comment by AndiDittrich** [comment]
added `gracefulExit` option (enabled by default) - https://github.com/npkgz/cli-progress/commit/17b9c642da9efed4ac4a226a6a3fe539c6d89d76

this works in most but not all cases
