### ISSUE TITLE
What about a bar.clear()?

### ISSUE THREAD

**Issue by stheine** [npkgz/cli-progress#96]
Hi,

on long-running jobs with a progress bar, I often have the need to print some extra log information in special situations.
as this interferes with the bar, I'd like the ability to completely clean out the bar, then print my log message, and then print the bar again in the next line.
currently, my workaround is:

> bar.stop();
> process.stdout.write('\x1b[1A                                                \r'); // add enough blanks to clear out the bar
> console.log('my log message');
> bar.start(total, num);

I would rather hope for
> bar.clear();
> console.log('my log message');
> ...
> bar.update(num); // this automatically draws the bar again on the next update

Regards
  stheine

**Comment by AndiDittrich** [comment]
there are some events available to print your messages, just take a look into the docs

**Comment by stheine** [comment]
not sure what you're referring to. I find many options to tweak the format of the bar itself, but when I'm logging extra data, that can be multi-line/ JSON.stringify/ colored, so I don't know how I could put that into the bar, that's why I'm rather completely removing the bar, then print my log data, then redraw the bar below my log output.

**Comment by AndiDittrich** [comment]
see #85 #57
but this method is intended for simple logging, not for fancy formatting. and as you might see by reading the previous issues regarding this feature request...it's quite complicated for multibars...

**Comment by stheine** [comment]
ok, get your point. of course, my workaround only works for the single bar mode - and that's fine for me, as that's all I use here - but you'd also have to cover the multi bar mode (unless you'd only offer that for single bar).
thanks for the pointers.
